#version 430

layout(local_size_x=1, local_size_y=1) in;
layout(r8ui, binding=0) uniform uimage2D image;
layout(std430, binding=1) buffer RBuffer {
	float red[];
};

void main()
{
	ivec2 pixelPos = ivec2(gl_GlobalInvocationID.xy);
	uint width = gl_NumWorkGroups.x;
	float val = red[pixelPos.x + pixelPos.y*width];
	uint valI = uint(val * 255.0);
	uvec4 pixel = uvec4(valI, valI, valI, 255);
	imageStore(image, pixelPos, pixel);
}

