#version 430

layout(local_size_x=1, local_size_y=1) in;
layout(std430, binding=0) buffer inputBuffer {
	vec4 input[];
};
layout(std430, binding=1) buffer bBuffer {
	vec4 b[];
};
layout(std430, binding=2) buffer cBuffer {
	vec4 c[];
};
layout(std430, binding=3) buffer dBuffer {
	vec4 d[];
};
layout(std430, binding=4) buffer eBuffer {
	vec4 e[];
};

void main()
{
	uint i = gl_GlobalInvocationID.x;
	input[i] = (b[i] * c[i]) - (d[i] * e[i]);
}

