#version 430

layout(local_size_x=1, local_size_y=128) in;
layout(std430, binding=0) buffer satBuffer {
	float sat[];
};
layout(std430, binding=1) buffer sumsBuffer {
	float sums[];
};

uniform uint width;
uniform uint height;

shared float offset;

void main()
{
	uint gidY = gl_GlobalInvocationID.y + 128;
	uint col = gl_GlobalInvocationID.x;
	if(gl_LocalInvocationID.y == 0) {
		offset = sums[col + gl_WorkGroupID.y*width];
	}
	barrier();
	if(gidY < height) sat[col + gidY*width] += offset;
}

