#version 430

layout(local_size_x=1, local_size_y=1) in;
layout(r8ui, binding=0) uniform uimage2D input;
layout(r8ui, binding=1) uniform uimage2D zeroOne;

void main()
{
	ivec2 pixelPos = ivec2(gl_GlobalInvocationID.xy);
	uvec4 zeroOneVal = imageLoad(zeroOne, pixelPos);
	uvec4 inputVal = imageLoad(input, pixelPos);
	inputVal.r = (zeroOneVal.r == 255) ? 255 : inputVal.r;
	inputVal.r = (zeroOneVal.r == 0) ? 0 : inputVal.r;
	imageStore(input, pixelPos, inputVal);
}

